runtime: php72

handlers:
- url: /
  script: index.php

# [START env]
env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  CLOUDSQL_USER: USER
  CLOUDSQL_PASSWORD: PASSWORD
  ##############################################################################
  # The CLOUDSQL_DSN below is used for instances of Cloud SQL running MySQL.   #
  # For instances of Cloud SQL running PostgreSQL, use the following           #
  # connection string instead:                                                 #
  #                                                                            #
  # CLOUDSQL_DSN: "pgsql:dbname=DATABASE;host=/cloudsql/CONNECTION_NAME"       #
  ##############################################################################
  CLOUDSQL_DSN: "mysql:dbname=DATABASE;unix_socket=/cloudsql/CONNECTION_NAME"
# [END env]

#[START cloudsql_settings]
# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
    cloud_sql_instances: "CONNECTION_NAME"
#[END cloudsql_settings]
